name = "CML NeoFFTV"
author = "karolkuter-boop"
version = "1.6.28"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "defa8bc5b64240a246b4f74f89cdee8a247904c4d37982a0b7c4f1d2aec05d96"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
