name = "CML NeoFFTV"
author = "karolkuter-boop"
version = "1.6.28"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3b10273873d0d9849267192622b455fcd60258dbbdac623705abb1a5f8ba5759"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
